ALTER TABLE subcategories
ADD COLUMN button_1_text TEXT DEFAULT NULL,
ADD COLUMN button_1_link TEXT DEFAULT NULL,
ADD COLUMN button_1_visible BOOLEAN DEFAULT FALSE,
ADD COLUMN button_2_text TEXT DEFAULT NULL,
ADD COLUMN button_2_link TEXT DEFAULT NULL,
ADD COLUMN button_2_visible BOOLEAN DEFAULT FALSE,
ADD COLUMN button_3_text TEXT DEFAULT NULL,
ADD COLUMN button_3_link TEXT DEFAULT NULL,
ADD COLUMN button_3_visible BOOLEAN DEFAULT FALSE;