ALTER TABLE public.hero_settings
  ADD COLUMN IF NOT EXISTS hero_visible BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS hero_text_part1_visible BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS hero_text_part2_visible BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS hero_animated_words_visible BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS animated_word_visibility BOOLEAN[] NOT NULL DEFAULT ARRAY[]::BOOLEAN[];

